package uk.ac.rhul.cs3821.dto;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Data Transfer Object representing user information.
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class UserDto {
  private Long id; // Auto-generated by the database (ignore on create)
  private String firebaseUid;
  private String firstName;
  private String lastName;
  private String username;
  private String email;
  private boolean active;
  private LocalDateTime emailVerifiedAt;
  private LocalDateTime lastLoginAt;
  private String profilePictureUrl;
  private String bio;
  private String phoneNumber;
  private String currency;
  private String preferredLanguage;
  private String timezone;
  private String role;
  private String theme;
  private LocalDateTime createdAt;
  private LocalDateTime updatedAt;
  private LocalDateTime deletedAt;

}
