spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/fyp
spring.datasource.username=postgres
spring.datasource.password=kayz123
spring.jpa.hibernate.ddl-auto=update
#use update when the database is stable
alphavantage.api-key=${ALPHA_VANTAGE_API_KEY:dummy-key}
alphavantage.base-url=https://www.alphavantage.co
marketaux.api.key=${MARKET_AUX_API_KEY:dummy}
marketaux.api.base-url=https://api.marketaux.com/v1/news/all
news.rotation.chunk-size=3
#spring.jpa.hibernate.ddl-auto=create-drop
# for the database is changing it will dele

